### ISSUE TITLE
Share resources between Flatmate programs.

### ISSUE THREAD

**Issue by huntc** [landlord/flatmate#12]
We have been discussing the need for Flatmate apps to be able to share objects between them, particularly Akka systems. Doing so should reduce the number of threads in use significantly e.g. perhaps by a factor of 5 for one of our own apps. This should reduce memory usage, and perhaps also improve CPU usage given the reduction in pinned IO threads polling EPOLL.

One thought was to leverage JNDI to share objects.

**Comment by stevewillcock** [comment]
Is there anything else to do on this one or did we forget to close it when the JNDI sharing PR was merged?

**Comment by huntc** [comment]
I think we can close it. :-)
